// Generated by CoffeeScript 1.4.0
(function() {
  var ResourceLimitType, mongoose;

  mongoose = require("mongoose");

  ResourceLimitType = {
    name: {
      type: String,
      required: true,
      trim: true
    },
    quantity: {
      type: Number,
      "default": 0
    }
  };

  exports.resourceLimits = function(schema, options) {
    if (!options) {
      options = {};
    }
    return schema.add({
      resourceLimits: {
        type: [ResourceLimitType],
        defaults: function() {
          return [];
        }
      }
    });
  };

}).call(this);
